### ISSUE TITLE
Impose common code style

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#140]
Next to having now somewhat sensible CONTRIBUTING.md, we should turn the guidelines described there into the `.clang-format` file. And maybe even automatically run `clang-format` on commits/pushes.

**Comment by vinipsmaker** [comment]
> Lines within 80 characters are preferred.

Is there a way to tell `clang-format` to _not_ reformat the line if it already fits in the 80 characters limit? I've been pissed off by related tools in other languages as these stylers can be a PITA.

**Comment by KitsuneRal** [comment]
No idea, not using `clang-format` yet.

**Comment by vinipsmaker** [comment]
Okay, I'll do a small test here after I finish the PRs to random projects I'm working on rn (I may not finish this today, and I don't have time in non-weekend days, so it may take a while). If `clang-format` misbehave, I'll open an issue on their repo and post the link here.

**Comment by KitsuneRal** [comment]
Thanks :)

**Comment by marcdeop** [comment]
I have started working on this. You can find the progress [here](https://github.com/marcdeop/libqmatrixclient/tree/140_impose_coding_standard).

As I was expecting, the code is not strict with the style in all files on the project and also some things are out of the standard Qt style.

So far I have tried to get as close as possible to Qt style and to the code that I already see in the classes. The last part that I am struggling with is the indentation of `public`, `private` access modifiers

**Comment by KitsuneRal** [comment]
@marcdeop please just fix the indentation to be more traditional, I really dislike the current one. It's probably worth to have a separate PR just for that.

**Comment by KitsuneRal** [comment]
Oh, and switch statements - can we please keep indentation 0 for `case` lines, and single indent for statements under them.

**Comment by KitsuneRal** [comment]
Closed by #295.
