### ISSUE TITLE
Use .well-known to resolve user homeserver

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#178]
Spec proposal https://docs.google.com/document/d/1vF-uWlUYmf1Xo161m871H1upJbwiIPeikWGWzaE_lrU

**Comment by Cadair** [comment]
FTR, this: https://github.com/QMatrixClient/libqmatrixclient/blob/master/lib/connection.cpp#L177 should be replaced with the well-known algorithm. (via @KitsuneRal in matrix)
