### ISSUE TITLE
Provide a colour code for the user

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#296]
This is to provide a common colour disambiguation functionality across clients. Ideally, it should be compatible with the Riot's algorithm, so that colours in Riot and QMatrixClient match. And then we'll spec it :-D

**Comment by a-andreyev** [comment]
provided [draft proposal via the wiki](https://github.com/QMatrixClient/libqmatrixclient/wiki/User-color-coding-standard-draft-proposal)

**Comment by KitsuneRal** [comment]
Closed by #298.
