### ISSUE TITLE
libQMatrixClient -> libQuotient

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#325]
Parts:
- [x] GitHub
- [x] Travis CI (nothing to do)
- [x] AppVeyor
- [x] BadgeApp
- [x] File system and CMake, including soname (no back comp)
- [x] C++ Namespace (with the back-comp synonym)
- [x] Strings
- [x] Logging categories
- [x] Documentation
- [x] References at matrix.org

**Comment by jubalh** [comment]
https://github.com/quotient-im/libQuotient/releases/tag/0.5.2 

> 0.5.x releases keep the previous library name, libQMatrixClient

But github will rename the tarball already ;) so after unpacking without specifying anything one will still get libQuotient-0.5.2. Just a hint.

**Comment by KitsuneRal** [comment]
Thanks. I advise against using those tarballs and checkout through git instead. Too bad I cannot switch off their generation.

**Comment by jubalh** [comment]
You can upload your own tarballs however.
Maybe take a look at https://github.com/blogc/blogc/releases
which has a note "Please download the custom tarballs, not the files generated automatically by GitHub, they are garbage."

And a list of alternative sources.

**Comment by KitsuneRal** [comment]
I'm not sure how much tarballs are even needed. But if they are, well those provided are not that bad. And the mess with names is for the transitional period anyway.
