### ISSUE TITLE
Configuring a room to use encryption

### ISSUE THREAD

**Issue by a-andreyev** [quotient-im/libQuotient#350]
To enable encryption in a room, a client should send a state event of type `m.room.encryption`, and content `{ "algorithm": "m.megolm.v1.aes-sha2" }` ([the docs](https://matrix.org/docs/spec/client_server/latest#m-megolm-v1-aes-sha2))

Probably `Q_INVOKABLE` method is needed for that or set method for the `usesEncryption` room property

**Comment by TobiasFella** [comment]
Implemented in 0209be8305aa38722a3d25593ae71fbb3ac05e52
