### ISSUE TITLE
Make building E2EE optional while it's not ready

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#369]
E2EE is far from being production-ready in Quotient, so it makes sense to put the E2EE stuff behind a build flag in order to simplify the build process.

**Comment by KitsuneRal** [comment]
Closed by #346.

**Comment by iyanmv** [comment]
E2EE is still disabled by default in 0.8. When should we expect this feature to be ready and enabled by default? I'm just asking because I would like to replace element with NeoChat at some point. Thanks for all the work btw 😉

**Comment by KitsuneRal** [comment]
There are a couple things that still need to land before I would consider it good enough to turn on by default: first, it simply needs some more testing (this is happening right now, by those who don't mind decryption failures all over the place); second, past history decryption has to be implemented and a few bugs around E2EE have to be fixed (you can find them here in the repo). All in all, I'm a bit reserved it will be ready for prime-time even in 0.9; more likely, some version after (1.0 or 0.10, it's undecided yet).
