### ISSUE TITLE
No Content-Length for empty POST requests

### ISSUE THREAD

**Issue by etherealvisage** [quotient-im/libQuotient#380]
### Description

Quaternion does not appear to send a `Content-Length` header for POST requests that have an empty body. This ends up with some Matrix homeservers returning a 411 (length required) for an otherwise-valid request. This appears specifically to be for servers that are proxied by lighttpd, which unlike other web servers that accept an empty body without a `Content-Length` header, lighttpd [rejects](https://serverfault.com/questions/315849/curl-post-411-length-required) [them](https://redmine.lighttpd.net/boards/3/topics/5851).

### Steps to reproduce

- Connect to Matrix homeserver proxied by lighttpd
- Perform some action that has an empty body (_e.g._ leaving a room)

Quaternion provides the following on stdout:

```
libqmatrixclient.jobs: "LeaveRoomJob" status 104: Error transferring https://<server>/_matrix/client/r0/rooms/!<room-id>:<server>/leave - server replied: Length Required
```

lighttpd's log files show the same thing:
```
<ip> - - [19/Feb/2020:03:10:21 +0000] "POST /_matrix/client/r0/rooms/!<room-id>:<server>/leave HTTP/1.1" 411 353 "-" "Mozilla/5.0"
```

This is really more a bug in `lighttpd` IMO, but it _does_ appear to be a valid reading of the RFC from what I can tell.

### Version information

- **The client application**: Quaternion v0.0.9.3

- **libQuotient version if you know it**: 0.4.0

- **Qt version**: 5.11.3

- **Install method**: from Debian repositories

- **Platform**: fairly standard Debian GNU/Linux derivative

**Comment by KitsuneRal** [comment]
Thanks for reporting. I'd say it's Qt's fault (especially given that Qt actively steps in and fills this header) but I think I know how to make it do the right thing. (Technical details: set the body to an empty `QByteArray` instead of `nullptr` to a `QIODevice`.)

**Comment by KitsuneRal** [comment]
This is fixed in the master branch and I can backport it to 0.5.x but libQMatrixClient 0.4.x is an unsupported branch as of now. Probably the right way would be to backport 0.5.x to Debian stable.
