### ISSUE TITLE
Alias updates don't trigger namesChanged()

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#390]
The `Q_PROPERTY` definitions for aliases imply that `namesChanged()` notifies about updates of those but that doesn't actually happen. To fix this the respective bitmask in `Room::updateData()` should be altered; this is pending the enum change proposed in #383.

**Comment by ram-nad** [comment]
Sir will adding a new line
```cpp
if (roomChanges & AliasesChange)
        emit namesChanged(this);
```

suffice?

**Comment by KitsuneRal** [comment]
You don't really need to add a line, there's already a check against `NameChange`. Just bit-OR `AliasesChange` to it. (It's fine to reuse #383 to fix this one, by the way.)
