### ISSUE TITLE
Direct chat room names empty

### ISSUE THREAD

**Issue by Midek** [quotient-im/libQuotient#394]
### Description

After updating to current master (0.0.9.4) most of the room names under tag 'People' are empty.
![pic](https://midov.pl/smiecioweobrazki/quaternion_bug.png)
Other rooms are unaffected.
In previous versions direct chat room names were displayed properly.

### Steps to reproduce

- perform clean login to the account

### Version information

- **Quaternion version**: 0.0.9.4
- **Qt version**: 5.14.1
- **Install method**: AUR Package
- **Platform**: Arch GNU/Linux

**Comment by KitsuneRal** [comment]
You should be good with the _current_ libQuotient master (no changes in Quaternion).
