### ISSUE TITLE
Use SPDX tags

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#426]
[SPDX](https://spdx.dev) tags have proven their worth for quite some time now, and the license headers throughout Quotient are in disorder - so let's fix this (and document).

**Comment by ognarb** [comment]
I did the first part of it and ported all the existing copyright statement to SPDX: https://github.com/quotient-im/libQuotient/pull/428 with licensedigger: https://invent.kde.org/sdk/licensedigger
