### ISSUE TITLE
DeviceKeys generated C++ bindings are missing the UnsignedDeviceInfo key

### ISSUE THREAD

**Issue by ognarb** [quotient-im/libQuotient#446]
See https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-keys-query

**Comment by KitsuneRal** [comment]
Not sure what's wrong here: I don't see the spec mentioning device keys in `unsigned`, but they should be there? It's a bug for the spec first off then.

**Comment by ognarb** [comment]
Actually, it's an error on my part, DeviceKeys shouldn't have an UnsignedDeviceInfo but DeviceInformation that inherit from UnsignedDeviceInfo should have it and it does.
