### ISSUE TITLE
Header files import wrong version of qt5

### ISSUE THREAD

**Issue by arnavr23** [quotient-im/libQuotient#482]
I have Ubuntu, and i was able to install the library with cmake, but the header files all import qt5 header files directly as <qt5core/qtutil>, instead of <qt5/qtcore/qutil>

**Comment by KitsuneRal** [comment]
Thanks for reporting; I'm afraid I need more information to understand what's going on. Where do you get your Qt from - does it come from Ubuntu's own repos or elsewhere? Do you have two Qt versions installed next to each other? `#include <QtCore/Q*>` is a pretty much official way to include Qt headers; to point to a specific Qt version, [you can pass `CMAKE_PREFIX_PATH` to CMake](https://github.com/quotient-im/libQuotient/blob/master/README.md#cmake-based), as described in README.md.

**Comment by arnavr23** [comment]
I downloaded qt from the ubuntu's apt, installed the qt5-default package. i ran this command before installing :
`"cmake ..  -DCMAKE_PREFIX_PATH="/usr/include/x86_64-linux-gnu/qt5;"`
still its showing the same error.

**Comment by KitsuneRal** [comment]
Which “same error” does it show? The original report didn’t have it. Which Ubuntu version do you use, and what is the version of `qt5-default` installed?

**Comment by arnavr23** [comment]
Oh sorry, it shows multiple errors like <QtNetwork/QNetworkAccessManager> not found, I use ubuntu 20.04, qt-default version is 5.12.8. I can access all my qt headers through qt5, so things like <qt5/QNetwork/QNetworkAccessManager> doesnt show any errors. Although the project compiled fine, and i was able to install it, i just cannot use it without it showing errors

**Comment by KitsuneRal** [comment]
Ah, so it’s not that building the library breaks, it’s about building your application on top of the library?

**Comment by arnavr23** [comment]
Yes

**Comment by KitsuneRal** [comment]
Ok - do you call `find_package` from your `CMakeLists.txt` file?

**Comment by arnavr23** [comment]
yes, I call find_package(Quotient)

**Comment by arnavr23** [comment]
I also call   find_package(Qt5 REQUIRED COMPONENTS Widgets Core Network) if that helps

**Comment by KitsuneRal** [comment]
Ok, does it actually find the library - did you try to add `REQUIRED` to the call?

The reason I’m asking all the questions is that Ubuntu is used in the continuous integration here and is not broken at the moment; so there’s an apparent misconfiguration at some step.

**Comment by arnavr23** [comment]
I think it finds the library, what it cant find is the Qt stuff like QtCore/QUrl

**Comment by arnavr23** [comment]
But it is able to recognize <qt5/QtCore/QUrl>
so I need a way to make it recognize qt libraries without adding qt5 to all header files

**Comment by arnavr23** [comment]
This is what it says : CMAKE_PREFIX_PATH:UNINITIALIZED="/usr/include/x86_64-linux-gnu/qt5;"

**Comment by KitsuneRal** [comment]
I just looked at your `CMAKE_PREFIX_PATH` again and realised that you passed include paths there - but you actually have to pass the path to the installation base part, such as `/usr` if you have Quotient installed at the system path. Speaking of which, why don’t you just install libQuotient via `apt install`?

**Comment by arnavr23** [comment]
for some reason, it cant locate libquotient, thats why(and yes i read the readme, so i tried its older name as well)

**Comment by KitsuneRal** [comment]
Where have you installed Quotient?

**Comment by arnavr23** [comment]
its installed at  /usr/local/include/Quotient

**Comment by KitsuneRal** [comment]
Oh, right, looks like libQuotient only came to hirsute (21.04)… and no please don’t use libqmatrixclient even if you find it in repos, it’s terribly old. Ok, so to which path did you install the (locally built) libQuotient?

**Comment by KitsuneRal** [comment]
Ah, alright, then your `CMAKE_PREFIX_PATH` should be `/usr/local`.

**Comment by arnavr23** [comment]
its locally cloned at /media/binarydigitz01/Programming Projects/c++/libraries/libQuotient, build at /media/binarydigitz01/Programming Projects/c++/libraries/libQuotient/build_dir

**Comment by KitsuneRal** [comment]
And be sure to use `REQUIRED` in `find_package`, it saves a lot of time when figuring out what’s wrong.

**Comment by KitsuneRal** [comment]
Did you pass '-DCMAKE_PREFIX_PATH=/usr/local` to CMake and did it complete without errors?

**Comment by arnavr23** [comment]
Should i do that to the library installation or to the project?

**Comment by KitsuneRal** [comment]
When configuring your project. The library is fine.

**Comment by arnavr23** [comment]
I did this: 'CMAKE_PREFIX_PATH:FILEPATH=/usr/local' in the cmake cache, and its still not working.

**Comment by arnavr23** [comment]
How should i import qt5 with cmake? i think thats where the problem lies, I am using find_package(qt5 REQUIRED)

**Comment by KitsuneRal** [comment]
Uhm, you’re really not supposed to edit `CmakeCache.txt`. For now, I recommend to just delete this file and run CMake again, passing the path as I advised.

If any library is installed at a default location, ` find_package` in `CMakeLists.txt` is enough. If it is a non-default location, like `/usr/local`, you should pass that location to CMake in `CMAKE_PREFIX_PATH` - it’s that simple. This is actually described in README.md to this library.

**Comment by KitsuneRal** [comment]
You may also want to look at how Quaternion does it: https://github.com/quotient-im/Quaternion/actions/runs/971613667/workflow#L198

**Comment by arnavr23** [comment]
Uhh its still not working, would you be kind enough to edit my CMakeLists.txt, and tell me what i am doing wrong?
` cmake_minimum_required(VERSION 3.0)                                                                                                          
  project(Matrix-client VERSION 1.0.0)                                                                                                         
                                                                                                                                               
  add_executable(matrix main.cpp)                                                                                                              
                                                                                                                                               
  # Libraries                                                                                                                                  
  find_package(Quotient REQUIRED)                                                                                                              
  find_package(Qt5 COMPONENTS Core Widgets REQUIRED)                                                                                           
  set(CMAKE_EXPORT_COMPILE_COMMANDS ON)                                                                                                        
  set(CMAKE_PREFIX_PATH /usr/local)                                                                                                            
`

**Comment by arnavr23** [comment]
Also, qt5 is located at these locations /usr/lib/x86_64-linux-gnu/qt5 /usr/lib/qt5 /usr/share/qt5, headers ar at  /usr/lib/x86_64-linux-gnu/qt5

**Comment by KitsuneRal** [comment]
> `set(CMAKE_PREFIX_PATH /usr/local)`

This shouldn't be here. First off, by this point in `CMakeLists.txt` it's already too late, all configuration happens when `find_package()` is invoked. Second, `CMAKE_PREFIX_PATH` is not supposed to be set inside `CMakeLists.txt`, at all. What you should do is call `cmake .. -DCMAKE_PREFIX_PATH=/usr/local` from your build directory.

As a result of that command, `find_package(Quotient REQUIRED)` will try to look into `/usr/local`, find necessary files under it (read [here]() if you're interested in gory details) and configure all compiler invocations to use additional include and linking flags that will point to: 1) Quotient include files; 2) the Quotient library; 3) paths to additional include files that Quotient may need (in particular, Qt5). All that will happen at `find_package(Quotient REQUIRED)`.

`find_package(Qt5 ...)` after that is only needed so that CMake knows that _your code_ (rather than libQuotient) needs Qt5 as well, and configure compiler invocations for those _your_ files that might not even call into Quotient at all. If you don't use Qt5 on top of what Quotient uses, you may omit this; but it's a good practice to be explicit about your dependencies rather than rely on indirect dependencies from libraries you use. In short, it's good that you have it around.

A takeaway for me here is that I just discovered valuable pieces about `CMAKE_PREFIX_PATH` to be mentioned in Quaternion's README.md but not in libQuotient's README.md. I will move them here as well.

**Comment by KitsuneRal** [comment]
I'm closing this as `invalid` since it's not a problem with the library - but feel free to ask more questions if you still have trouble building it.

**Comment by arnavr23** [comment]
I finally made it detect qt libraries, now the build errors are : /usr/bin/ld: CMakeFiles/helloworld.dir/main.cpp.o: in function `Quotient::TagEvent::TagEvent(QJsonObject)':
main.cpp:(.text._ZN8Quotient8TagEventC2E11QJsonObject[_ZN8Quotient8TagEventC5E11QJsonObject]+0x39): undefined reference to `Quotient::Event::Event(unsigned long, QJsonObject const&)'
/usr/bin/ld: CMakeFiles/helloworld.dir/main.cpp.o: in function `auto Quotient::setupFactory<Quotient::TagEvent>()':
main.cpp:(.text._ZN8Quotient12setupFactoryINS_8TagEventEEEDav[_ZN8Quotient12setupFactoryINS_8TagEventEEEDav]+0x42): undefined reference to `EVENTS()'
/usr/bin/ld: CMakeFiles/helloworld.dir/main.cpp.o: in function `Quotient::ReadMarkerEvent::ReadMarkerEvent(QJsonObject)':
main.cpp:(.text._ZN8Quotient15ReadMarkerEventC2E11QJsonObject[_ZN8Quotient15ReadMarkerEventC5E11QJsonObject]+0x39): undefined reference to `Quotient::Event::Event(unsigned long, QJsonObject const&)'
/usr/bin/ld: CMakeFiles/helloworld.dir/main.cpp.o: in function `auto Quotient::setupFactory<Quotient::ReadMarkerEvent>()':
main.cpp:(.text._ZN8Quotient12setupFactoryINS_15ReadMarkerEventEEEDav[_ZN8Quotient12setupFactoryINS_15ReadMarkerEventEEEDav]+0x42): undefined reference to `EVENTS()'
/usr/bin/ld: CMakeFiles/helloworld.dir/main.cpp.o: in function `Quotient::IgnoredUsersEvent::IgnoredUsersEvent(QJsonObject)':
main.cpp:(.text._ZN8Quotient17IgnoredUsersEventC2E11QJsonObject[_ZN8Quotient17IgnoredUsersEventC5E11QJsonObject]+0x39): undefined reference to `Quotient::Event::Event(unsigned long, QJsonObject const&)'
/usr/bin/ld: CMakeFiles/helloworld.dir/main.cpp.o: in function `auto Quotient::setupFactory<Quotient::IgnoredUsersEvent>()':
main.cpp:(.text._ZN8Quotient12setupFactoryINS_17IgnoredUsersEventEEEDav[_ZN8Quotient12setupFactoryINS_17IgnoredUsersEventEEEDav]+0x42): undefined reference to `EVENTS()'

**Comment by KitsuneRal** [comment]
How does your `target_link_libraries()` line look?

**Comment by arnavr23** [comment]
target_link_libraries(helloworld Qt5::Widgets Qt5::Network )

**Comment by KitsuneRal** [comment]
Well, as you can see, all missing symbols come from Quotient, and you haven’t linked to `Quotient`.

**Comment by arnavr23** [comment]
oh yeah...

**Comment by arnavr23** [comment]
I think it should be mentioned in the readme.md along with the find_package stuff

**Comment by arnavr23** [comment]
It builds now, thanks for your time!
