### ISSUE TITLE
High amount of log spam from `BaseJob::sendRequest` and `BaseJob::checkReply`

### ISSUE THREAD

**Issue by patlefort** [quotient-im/libQuotient#502]
### Description

High amount of logging from `BaseJob::sendRequest` and `BaseJob::checkReply` from usage of qCInfo. Should it print this information with qCDebug instead? Should libQuotient be compiled with QT_NO_INFO_OUTPUT? Or is the user expected to turn off the output with an environment variable? Is neochat making proper use of libQuotient? I generally don't need this information unless the response is an http error, so maybe it should output only in case of errors?

### Steps to reproduce

Using neochat.

### Version information

- Neochat (ver 1.2.0)

- libQuotient 0.6.8

- QT 5.15.2 

- Installed from package manager

- Arch Linux

**Comment by KitsuneRal** [comment]
Most of these requests are actually about thumbnails that will go away once the transition to a different retrieval mechanism will be done. But I think I can provide some alleviation for libQuotient 0.6.9 as well.
