### ISSUE TITLE
E2EE database is being cleared on login

### ISSUE THREAD

**Issue by hugohn** [quotient-im/libQuotient#546]
**Describe the bug**
The E2EE database, which includes all Olm/MegOlm session data, is being cleared on login in [PR#477](https://github.com/quotient-im/libQuotient/pull/477).

https://github.com/quotient-im/libQuotient/blame/b865be5ad72b3996bf072268d061d7466bf4623a/lib/connection.cpp#L538

**To Reproduce**
Steps to reproduce the behaviour, and the description of the actual result:
1. Log in and join an encrypted room
2. Verify that client can decrypt incoming encrypted messages
3. Log out then log in again, client fails to decrypt messages that it previously decrypted successfully

**Expected behavior**
Client should be able to decrypt messages when logging in to an existing account.

**Is it environment-specific?**
No

**Additional context**
Commenting out the `database->clear();` command fixes the issue.

**Comment by TobiasFella** [comment]
That's intentional:
- The database should really be cleared when logging out, doing it during login is just an extra step to make sure we have a clean environment
- We use a new database file for each login session (so this step really is pointless, it's still from an older version)
- We can't reuse some parts (account keys, etc.)
- We shouldn't reuse the rest either

**Comment by hugohn** [comment]
@TobiasFella Thank you for the comment. For those who are not clear, what Tobias is referring to with respect to clearing data on logout, is mentioned here in the Matrix client-server API spec: https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3logout

Tobias, I understand the requirement to clear data on logout. 

But I think clearing data on login is still not quite right. When you log in for the second time with the same device_id (and get a new access_token), the SDK shouldn't clear the existing keys/Olm sessions belonging to that device_id. The spec mentions nothing about clearing data on login.

AFAIK, Matrix iOS SDK and Android SDK are also not doing that (and keys/Olm sessions can be reused without issues):
https://github.com/matrix-org/matrix-ios-sdk
https://github.com/matrix-org/matrix-android-sdk2

Am I missing something?

**Comment by hugohn** [comment]
https://spec.matrix.org/latest/#devices

> When a user first uses a client, it registers itself as a new device. The longevity of devices might depend on the type of client. **A web client will probably drop all of its state on logout, and create a new device every time you log in, to ensure that cryptography keys are not leaked to a new user. In a mobile client, it might be acceptable to reuse the device if a login session expires, provided the user is the same**.

To me, this paragraph here in the spec implies that both device_id AND cryptographic keys can be reused. Particularly when a login session expires and the user needs to log in again.

**Comment by hugohn** [comment]
Any comments here @TobiasFella @KitsuneRal ? Is my understanding incorrect w.r.t. the spec?

**Comment by KitsuneRal** [comment]
I think Tobias is correct: https://spec.matrix.org/v1.3/client-server-api/#soft-logout - this is what you call "expiry" of the login, and in that case we shouldn't dismiss the database but if it's an explicit logout then it's all gone.

**Comment by KitsuneRal** [comment]
To be clear: soft logout is not (yet) supported by libQuotient but [it should](https://github.com/quotient-im/libQuotient/issues/259). Also, maybe clients should less aggressively logout on exit (at least ask about that...).
