### ISSUE TITLE
Encryption key is not sent after few days or 100 messages

### ISSUE THREAD

**Issue by Akselmo** [quotient-im/libQuotient#610]
**Describe the bug**

Basically this bug: https://bugs.kde.org/show_bug.cgi?id=463705

> Neochat stops sending keys for messages after few days of using E2EE.
> 
> When I'm chatting to someone with E2EE on in 1-1 chat, the chat works fine for a few days. 
> Both users can see both messages.
> 
> After 4-5 days, Neochat stops sending the encryption keys to the other participant *and* this
> can be seen in other clients too with the same account.
> 
> On Neochat, the message shows up like normal.
> On Element, both users get this message: 
> ** Unable to decrypt: The sender's device has not sent us the keys for this message. **
> 
> After logging out and logging back in to Neochat, the keys are being sent again. 
> Restarting Neochat is not enough, you have to completely log out and log back in.

We chatted with @TobiasFella on Neochat matrix channel about it. 

Basically what he thinks it might be is that there's no encryption key sent for the new megolm session that is created after one week or 100 messages.

**To Reproduce**
Steps to reproduce the behaviour, and the description of the actual result:
1. Start E2EE chat with someone, either through Element or Neochat. (In my case, this same chat was started from Element long time ago)
2. E2EE works fine for few days
3. At some point, Neochat stops sending the keys to other clients. On Neochat, you can see your messages normally. Other clients cant see your message, even on your own account.
4. Log out from Neochat
5. Log back in to Neochat
6. E2EE messages can be sent normally again from Neochat, and the error is gone.

**Expected behavior**
E2EE keys are not being sent according to Element and other clients.

Also if you think this is something trivial to fix, maybe I could give it a try? :) I am interested in learning how Matrix works, but this may be way out of my league...

**Comment by Akselmo** [comment]
The bug happened again. Took 5 days for it to happen, so I guess 5 days is when the encryption key needs to be sent to the new megolm session?

**Comment by KitsuneRal** [comment]
Sorry for taking time. Ok, if you want to try this guess out, here's what I would do.

First, enable the E2EE logging category (see the library's README how to do that; you need `quotient.e2ee.debug=true`, namely). Reproduce the problem (if Tobias' guess is right, it probably doesn't matter whether the trigger is time or the number of messages, so to save time you can just send 100 messages in an encrypted room). When the Megolm session gets rotated, you will see a message in the logs: "Creating new outbound megolm session". If it doesn't occur _and_ other clients stop being able to decrypt the events - there's a problem even with the session creation; but this is unlikely.

So if that message in the logs shows up - the code that actually sends the new session key is inside `Connection::sendSessionKeyToDevices()` (see `connection.cpp`) and it's called from `Room::Private::doSendEvent()`. Again, you will see in the logs if that actually happens, the message should be "Sending room key to devices", with the new session ID following. If that doesn't happen - you'll have to debug `R::P::doSendEvent()` to understand why it doesn't call `C::sendSessionKeyToDevices()`.

Now, if that message is also there in the logs, we have to go through `sendSessionKeyToDevices()` in order to understand two things: 1) whether it collects the right list of target devices (again, you can see it from the logs but you might even want to break and step over the loop in the beginning of the method); and 2) whether it actually sends the request - this can also be found from the logs (each request is sent within a "job" so you need to have `quotient.jobs.debug` logging category enabled to check this), if the request is actually sent you should see a bunch of log lines about the `/sendToDevice` job.

Let me know about your findings :)

**Comment by Akselmo** [comment]
Ok, I can try to look into this When I Got Time™️ Thanks for the explanation. 

But of course if you or anyone else who might be reading this figures it out before me, no need to wait for me! :joy:

**Comment by Akselmo** [comment]
I have now confirmed that the bug happens after 100 messages. I used this tiny script with Neochat to confirm it

```python
import os
import time

print("Starting message spam from 1 to 104")
time.sleep(5)
for i in range(1,105):
    os.system(f"ydotool type {i}")
    time.sleep(0.5)
    os.system("ydotool key 28:1 28:0")
    time.sleep(1)

print("Done")
```

I see if I can get some logs as well

**Comment by Akselmo** [comment]
Here's some E2EE logs from the moment the key changes

```sh
quotient.e2ee: Encrypted event from "@akselmo:matrix.akselmo.dev"
quotient.e2ee: Sending room key to devices: "dUCrsgKk3ld7o3CZfjpCeAEPzrRkyLRAOKjaLkt5kW4" 99
quotient.e2ee: Encrypted event from "@akselmo:matrix.akselmo.dev"
quotient.e2ee: Creating new outbound megolm session for room  "!NenIgaqPaTYiyHsFgQ:matrix.org"
quotient.e2ee: Allocated 256 bytes of secure heap (requested 160 bytes), 608 / 65536 bytes of secure heap used in total
quotient.e2ee: Deallocated 256 bytes, 352 / 65536 bytes of secure heap used

// The following keys stop working

quotient.e2ee: Adding inbound session "F4XBS129dMeJ5pBVCSkzM6M8I62kTTx/i/O+/u6oxgs"
quotient.e2ee: Sending room key to devices: "F4XBS129dMeJ5pBVCSkzM6M8I62kTTx/i/O+/u6oxgs" 0
quotient.e2ee: Encrypted event from "@akselmo:matrix.akselmo.dev"
quotient.e2ee: Consuming 1 to-device events
quotient.e2ee: Sending room key to devices: "F4XBS129dMeJ5pBVCSkzM6M8I62kTTx/i/O+/u6oxgs" 1
quotient.e2ee: Encrypted event from "@akselmo:matrix.akselmo.dev"
quotient.e2ee: Sending room key to devices: "F4XBS129dMeJ5pBVCSkzM6M8I62kTTx/i/O+/u6oxgs" 2
quotient.e2ee: Encrypted event from "@akselmo:matrix.akselmo.dev"
quotient.e2ee: Consuming 1 to-device events
```

**Comment by Akselmo** [comment]
Here's with jobs debug log enabled

```sh
quotient.e2ee: Sending room key to devices: "P6hFlWi0MYN2pqOmu/H9cdwDWAG/j2XyJVH871mJOUA" 99
quotient.jobs: Sent PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/send/m.room.encrypted/DYVKWTJDNI1678544590874201
quotient.jobs: Sent PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/typing/%40akselmo%3Amatrix.akselmo.dev
quotient.jobs: 200 <- PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/typing/%40akselmo%3Amatrix.akselmo.dev
quotient.jobs: "SetTypingJob" destroyed
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: 200 <- PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/send/m.room.encrypted/DYVKWTJDNI1678544590874201
quotient.jobs: "SendMessageJob" destroyed
quotient.e2ee: Encrypted event from "@akselmo:matrix.akselmo.dev"
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: Sent POST https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/read_markers
quotient.jobs: 200 <- POST https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/read_markers
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "SetReadMarkerJob" destroyed
quotient.jobs: Sent PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/typing/%40akselmo%3Amatrix.akselmo.dev
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: 200 <- PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/typing/%40akselmo%3Amatrix.akselmo.dev
quotient.jobs: "SetTypingJob" destroyed
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.e2ee: Creating new outbound megolm session for room  "!NenIgaqPaTYiyHsFgQ:matrix.org"
quotient.e2ee: Allocated 256 bytes of secure heap (requested 160 bytes), 624 / 65536 bytes of secure heap used in total
quotient.e2ee: Deallocated 256 bytes, 368 / 65536 bytes of secure heap used
quotient.e2ee: Adding inbound session "DSpBcQ2LBG7v7iGgCDgyB/o8OyUqwVq33RHdceG6n/c"
quotient.e2ee: Sending room key to devices: "DSpBcQ2LBG7v7iGgCDgyB/o8OyUqwVq33RHdceG6n/c" 0
quotient.jobs: Sent PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/send/m.room.encrypted/DYVKWTJDNI1678544590874203
quotient.jobs: Sent PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/typing/%40akselmo%3Amatrix.akselmo.dev
quotient.jobs: 200 <- PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/typing/%40akselmo%3Amatrix.akselmo.dev
quotient.jobs: "SetTypingJob" destroyed
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: 200 <- PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/send/m.room.encrypted/DYVKWTJDNI1678544590874203
quotient.jobs: "SendMessageJob" destroyed
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.e2ee: Encrypted event from "@akselmo:matrix.akselmo.dev"
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.e2ee: Consuming 1 to-device events
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: Sent POST https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/read_markers
quotient.jobs: Sent PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/typing/%40akselmo%3Amatrix.akselmo.dev
quotient.jobs: 200 <- POST https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/read_markers
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "SetReadMarkerJob" destroyed
quotient.jobs: 200 <- PUT https://matrix.akselmo.dev/_matrix/client/v3/rooms/%21NenIgaqPaTYiyHsFgQ%3Amatrix.org/typing/%40akselmo%3Amatrix.akselmo.dev
quotient.jobs: "SetTypingJob" destroyed
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
quotient.jobs: Sent GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: 200 <- GET https://matrix.akselmo.dev/_matrix/client/v3/notifications
quotient.jobs: "GetNotificationsJob" destroyed
```

I can't see `/sendToDevice` logs here, unless those PUT messages are them.

Also, seems when I reached 100 messages, Nheko suddenly gave me a warning that the device (Neochat after 100 messages) is unverified.

**Comment by Akselmo** [comment]
Is the hash empty here and thus nothing happens? https://github.com/quotient-im/libQuotient/blob/3c1c4f04b7756e276b033fb41399af727e824cec/lib/connection.cpp#L2445
