### ISSUE TITLE
Pinned messages event is not what is specced

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#676]
It uses `m.room.pinned_messages` instead of `m.room.pinned_events` for the type, and `pinned_events` instead of `pinned` for the key name in the event content. Not sure it ever worked (i.e. it could work within libQuotient ecosystem; but could not be interoperable with other clients). Or, even more embarrasingly, we've got the spec wrong and "all" clients use a non-specced event.

**Comment by CarlSchwan** [comment]
We don't implement this feature in NeoChat yet...
