### ISSUE TITLE
Wrong required library name libQuotientQt60_8

### ISSUE THREAD

**Issue by ecsgh** [quotient-im/libQuotient#681]
**Describe the bug**
When i build an rpm package, the generated package provide libQuotientQt6-0_8.
But the generated devel package require libQuotientQt60_8.
Without "-".
This is done automatically.
Think this i a bug and the devel sould also require libQuotientQt6-0_8

**To Reproduce**
Steps to reproduce the behaviour, and the description of the actual result:
1. Make a rpm spec and build package
2. After that devel-package require libQuotientQt60_8 = 0.8.0
3. 

**Expected behavior**
I expected, that the devel package also require libQuotientQt6-0_8 and not libQuotientQt60_8.
So i do not must extra instert following in spec file.
Provides:       %{name}%{soversion} = %{version}

**Comment by KitsuneRal** [comment]
Well, the bug seems to be in the spec file? This repo is not exactly for that but as I have some experience with rpm building - would you show me the spec file?

**Comment by ecsgh** [comment]
https://build.opensuse.org/package/view_file/home:ecsos:messenger:matrix/libQuotientQt6/libQuotientQt6.spec?expand=1

**Comment by KitsuneRal** [comment]
Well, it requires what you ask it to require - I see this inside `%package devel`:
```
Requires:       %{name}%{soversion} = %{version}
```
Change the requirement to `%{name}-%{soversion} = %{version}` if that's what you intended.

**Comment by ecsgh** [comment]
I think the name libQuotientQt60_8 is wrong.
When I build libQuotient, the following prrovides are generated automatically:
libQuotientQt6-0_8 = 0.8.0-lp155.3.1 	
libQuotientQt6-0_8(x86-64) = 0.8.0-lp155.3.1 	
libQuotientQt6.so.0.8()(64bit)
libQuotientQt6-0_8 = 0.8.0-lp155.3.1
Which would be correct according to my understanding.
But the devel-package requires libQuotientQt60_8. 
I added the line "Requires: %{name}%{soversion} = %{version}" manually, so that you can use libQuotient-devel as a dependency at all. So a dirty fix, so to speak.
So I would have expected the devel-package to require libQuotientQt6-0_8. But it doesn't. And only for that reason I had to add the above line. Not because I wanted to, but because I think the devel-package is asking for it incorrectly.

For this reason this issue must not be closed, because it is not solved.
Please open again and fix it, please.

**Comment by ecsgh** [comment]
Am Sonntag, 16. Juli 2023, 11:26:06 CEST schrieb Alexey Rusakov:
> Closed #681 as completed.

I think it is not fixed.

Read on github.

Regards
 Eric

**Comment by KitsuneRal** [comment]
This repo has nothing to do with RPMs; I have no idea what you want me to fix. At the same time I see an obviously incorrect `Requires` in your spec file. What exactly happens if you remove this dirty fix?

**Comment by ecsgh** [comment]
If I remove that, then quaternion can't be built because libQuotient-devel can't find libQuotient itself.
But I have now solved it differently. Thanks anyway.
