### ISSUE TITLE
ABI break in patch version 0.8.1

### ISSUE THREAD

**Issue by antonio-rojas** [quotient-im/libQuotient#702]
Commit https://github.com/quotient-im/libQuotient/commit/d850d153ba4f0b34f280ec3cbec0efb2736d1ba4, included in 0.8.1, breaks the ABI between patch versions, which contradicts the ABI stability claimed in the README https://github.com/quotient-im/libQuotient#apiabi-stability

**Comment by KitsuneRal** [comment]
Heh, true, it is API-compatible but I forgot about ABI :-/
