### ISSUE TITLE
Getting room keys

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#90]
This means processing `m.room_key` events. They arrive in the `to_device` section of `/sync` return, so the pre-requisite for this is ability to receive to-device messages.

**Comment by a-andreyev** [comment]
Introduced in #346 (b485cfdd3f5f2abb06471fd8523d5be80874ca25 and 0c01ece25b14b8600dc4dfb4fa6192349d2cbff9)
