### ISSUE TITLE
Extend support of m.room.encryption events

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#95]
In order to properly rotate Megolm sessions, the library should detect and store rotation criteria that arrive in `m.room.encryption` events: `rotation_period_msgs` and `rotation_period_ms`.

**Comment by a-andreyev** [comment]
Detected, but not stored/processed within a room yet

**Comment by KitsuneRal** [comment]
Actually, they _are_ stored, because `Room` stores all state events as they are; just not actually put to use.

**Comment by KitsuneRal** [comment]
Considering this closed by the above-mentioned commits.
